# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'graphics/kdiagram' : '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/incidenceeditor' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kldap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kitemviews': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kholidays': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@latest-kf6'

Options:
  cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
  require-passing-tests-on: [ '@all' ]
  cppcheck-arguments: '--enable=warning,performance,portability,style,unusedFunction --suppress-xml=cppcheck-suppressions.xml'
  require-cppcheck-clean: True
  cppcheck-ignore-files:
    - src/autotests
    - src/activities/autotests
    - src/views/collectionview/autotests
    - src/kontactplugin/korganizer/autotests
    - src/views/collectionview/reparentingmodel.cpp
    - plugins/hebrew
