# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'graphics/kdiagram' : '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-calendar' : '@latest-kf6'
    'pim/akonadi-contacts' : '@latest-kf6'
    'pim/akonadi-notes' : '@latest-kf6'
    'pim/calendarsupport' : '@latest-kf6'
    'pim/eventviews' : '@latest-kf6'
    'pim/incidenceeditor' : '@latest-kf6'
    'pim/kcalutils' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kldap' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'libraries/kuserfeedback': '@latest-kf6'
