# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'extragear/graphics/kdiagram' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-calendar' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/akonadi-notes' : '@same'
    'kde/pim/calendarsupport' : '@same'
    'kde/pim/eventviews' : '@same'
    'kde/pim/incidenceeditor' : '@same'
    'kde/pim/kcalutils' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kldap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kontactinterface' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/pimcommon' : '@same'
