# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'graphics/kdiagram' : '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/incidenceeditor' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kldap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@latest-kf6'

Options:
  cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
  require-passing-tests-on: [ '@all' ]
  cppcheck-arguments: '--enable=warning,performance,portability,style,unusedFunction --suppress-xml=cppcheck-suppressions.xml'
  require-cppcheck-clean: True
  enable-lsan: True
  cppcheck-ignore-files:
    - src/autotests
    - src/activities/autotests
    - src/views/collectionview/autotests
    - src/kontactplugin/korganizer/autotests
    - src/views/collectionview/reparentingmodel.cpp
    - plugins/hebrew
