/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a korganizeradaptor -- org.kde.korganizer.Korganizer.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KORGANIZERADAPTOR_H_209281151075056
#define KORGANIZERADAPTOR_H_209281151075056

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.korganizer.Korganizer
 */
class KorganizerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.korganizer.Korganizer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.korganizer.Korganizer\" >\n"
"    <method name=\"openURL\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"mergeURL\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"closeURL\" />\n"
"    <method name=\"saveURL\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"saveAsURL\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"getCurrentURLasString\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"editIncidence\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"deleteIncidence\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"deleteIncidence\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"in\" type=\"b\" name=\"force\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"addIncidence\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"ical\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"showIncidence\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"uid\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"showIncidenceContext\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"uid\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KorganizerAdaptor(QObject *parent);
    virtual ~KorganizerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool addIncidence(const QString &ical);
    void closeURL();
    bool deleteIncidence(const QString &url, bool force);
    bool deleteIncidence(const QString &url);
    bool editIncidence(const QString &url);
    bool getCurrentURLasString();
    bool mergeURL(const QString &url);
    bool openURL(const QString &url);
    bool saveAsURL(const QString &url);
    bool saveURL();
    bool showIncidence(const QString &uid);
    bool showIncidenceContext(const QString &uid);
Q_SIGNALS: // SIGNALS
};

#endif
