{
    "KPlugin": {
        "Description": "Kontact KOrganizer Plugin",
        "Description[ar]": "ملحقة «منظّمك» لِ‍«متراسلك»",
        "Description[az]": "Kontact KOrganizer plaqini",
        "Description[bg]": "Приставка Kontact за KOrganizer",
        "Description[ca@valencia]": "Connector de KOrganizer de Kontact",
        "Description[ca]": "Connector del KOrganizer del Kontact",
        "Description[de]": "KOrganizer-Modul für Kontact",
        "Description[en_GB]": "Kontact KOrganizer Plugin",
        "Description[eo]": "Kontact-KOrganizilo-kromaĵo",
        "Description[es]": "Complemento de KOrganizer para Kontact",
        "Description[fi]": "Kontactin KOrganizer-liitännäinen",
        "Description[fr]": "Module externe « KOrganizer » pour Kontact",
        "Description[ia]": "Plug-in Kontact KOrganizer",
        "Description[id]": "Plugin KOrganizer Kontact",
        "Description[it]": "Estensione per Kontact di KOrganizer",
        "Description[ka]": "KOrganizer-ის დამატება Kontact-ისთვის",
        "Description[ko]": "Kontact KOrganizer 플러그인",
        "Description[nl]": "Kontact KOrganizer-plug-in",
        "Description[pl]": "Wtyczka Kontact do współpracy z KOrganizerem",
        "Description[pt]": "'Plugin' do KOrganizer para o Kontact",
        "Description[pt_BR]": "Plugin do KOrganizer para o Kontact",
        "Description[ru]": "Календарь",
        "Description[sl]": "Vstavek Kontact za KOrganizer",
        "Description[sv]": "Kontact-insticksprogram för Korganizer",
        "Description[tr]": "Kontak K Organizatör Eklentisi",
        "Description[uk]": "Додаток календаря KOrganizer для Kontact",
        "Description[x-test]": "xxKontact KOrganizer Pluginxx",
        "Description[zh_CN]": "Kontact KOrganizer 插件",
        "EnabledByDefault": true,
        "Icon": "view-pim-calendar",
        "Id": "kontact_korganizerplugin",
        "License": "GPL",
        "Name": "Calendar",
        "Name[af]": "Kalender",
        "Name[ar]": "التّقويم",
        "Name[az]": "Təqvim",
        "Name[bg]": "Календар",
        "Name[br]": "Deiziadur",
        "Name[bs]": "Kalendar",
        "Name[ca@valencia]": "Calendari",
        "Name[ca]": "Calendari",
        "Name[cs]": "Kalendář",
        "Name[cy]": "Calendr",
        "Name[da]": "Kalender",
        "Name[de]": "Kalender",
        "Name[el]": "Ημερολόγιο",
        "Name[en_GB]": "Calendar",
        "Name[eo]": "Kalendaro",
        "Name[es]": "Calendario",
        "Name[et]": "Kalender",
        "Name[eu]": "Egutegia",
        "Name[fa]": "تقویم",
        "Name[fi]": "Kalenteri",
        "Name[fr]": "Calendrier",
        "Name[fy]": "Aginda",
        "Name[ga]": "Féilire",
        "Name[gl]": "Calendario",
        "Name[he]": "לוח שנה",
        "Name[hu]": "Naptár",
        "Name[ia]": "Calendario",
        "Name[id]": "Kalender",
        "Name[is]": "Dagatal",
        "Name[it]": "Calendario",
        "Name[ja]": "カレンダー",
        "Name[ka]": "კალენდარი",
        "Name[kk]": "Күнтізбе",
        "Name[km]": "ប្រតិទិន",
        "Name[ko]": "달력",
        "Name[lt]": "Kalendorius",
        "Name[lv]": "Kalendārs",
        "Name[mai]": "कैलेंडर",
        "Name[mk]": "Календар",
        "Name[mr]": "दिनदर्शिका",
        "Name[ms]": "Kalendar",
        "Name[nb]": "Kalender",
        "Name[nds]": "Kalenner",
        "Name[ne]": "क्यालेन्डर",
        "Name[nl]": "Agenda",
        "Name[nn]": "Kalender",
        "Name[pa]": "ਕੈਲੰਡਰ",
        "Name[pl]": "Kalendarz",
        "Name[pt]": "Calendário",
        "Name[pt_BR]": "Calendário",
        "Name[ro]": "Calendar",
        "Name[ru]": "Календарь",
        "Name[se]": "Kaleandar",
        "Name[sk]": "Kalendár",
        "Name[sl]": "Koledar",
        "Name[sr@ijekavian]": "Календар",
        "Name[sr@ijekavianlatin]": "Kalendar",
        "Name[sr@latin]": "Kalendar",
        "Name[sr]": "Календар",
        "Name[sv]": "Kalender",
        "Name[ta]": "நாள்காட்டி",
        "Name[tg]": "Тақвим",
        "Name[th]": "ปฏิทิน",
        "Name[tr]": "Takvim",
        "Name[ug]": "يىلنامە",
        "Name[uk]": "Календар",
        "Name[uz@cyrillic]": "Календар",
        "Name[uz]": "Kalendar",
        "Name[wa]": "Calindrî",
        "Name[x-test]": "xxCalendarxx",
        "Name[zh_CN]": "日历",
        "Name[zh_TW]": "行事曆",
        "Version": "0.1",
        "Website": "https://kontact.kde.org/components/korganizer/"
    },
    "X-KDE-ConfigModuleNamespace": "pim@QT_MAJOR_VERSION@/kcms/korganizer/",
    "X-KDE-KontactPartExecutableName": "korganizer",
    "X-KDE-KontactPartLibraryName": "korganizerpart",
    "X-KDE-KontactPluginHasSummary": true,
    "X-KDE-KontactPluginVersion": 11,
    "X-KDE-Weight": 400
}
